import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'en': {
      'appTitle': 'Kabadiwala Connect',
      'home': 'Home',
      'createLot': 'Create Lot',
      'camera': 'Camera',
      'takePhoto': 'Take Photo',
      'takePhotoPrompt': 'Take or Choose Material Photo',
      'retake': 'Retake',
      'retakePhoto': 'Retake Photo',
      'chooseGallery': 'Choose from Gallery',
      'continueToDetails': 'Continue to Details',
      'skipPhoto': 'Skip Photo',
      'material': 'Material',
      'selectCategory': 'Select Material Category',
      'weight': 'Weight',
      'enterWeight': 'Enter Weight (kg)',
      'condition': 'Condition',
      'selectCondition': 'Select Condition',
      'conditionGood': 'Working (Good)',
      'conditionAverage': 'Used (Average)',
      'conditionScrap': 'Scrap (Broken)',
      'save': 'Save',
      'saveLot': 'Save Lot Locally',
      'priceBoard': 'Price Board',
      'indicativePrice': 'Indicative Price',
      'listen': 'Listen',
      'listening': 'Playing Audio...',
      'earnings': 'Earnings',
      'earningsLedger': 'Earnings Ledger',
      'totalEarnings': 'Total Earnings',
      'currentMonthEarnings': 'Current Month Earnings',
      'paid': 'Paid',
      'pending': 'Pending',
      'paymentStatus': 'Payment Status',
      'offline': 'Offline',
      'offlineModeActive': 'Offline Mode Active • Saved in SQLite',
      'onlineConnected': 'Online • Synced with Cloud',
      'noInternet': 'No Internet',
      'waitingForInternet': 'Waiting for internet',
      'synced': 'Synced',
      'syncing': 'Syncing...',
      'failed': 'Failed',
      'syncFailed': 'Sync Failed',
      'pendingSync': 'Pending Sync',
      'retry': 'Retry',
      'retrySync': 'Retry Sync',
      'syncNow': 'Sync Now',
      'lastUpdated': 'Last updated',
      'updatedToday': 'Updated today',
      'noTransactions': 'No transactions recorded yet.',
      'noLots': 'No material lots recorded yet.\nTap "Create Lot" to start.',
      'recordedLots': 'Recorded Lots',
      'source': 'Source',
      'location': 'Location',
      'finalAmount': 'Final Amount',
      'recycler': 'Recycler',
      'refreshPrices': 'Refresh Rates',
      'refreshLedger': 'Refresh Ledger',
      'allTransactions': 'All Transactions',
      'all': 'All',
      'indicativeRates': 'Indicative Market Rates',
      'liveRates': 'Live Market Rates',
      'cachedOfflineRates': 'Cached Offline Rates (SQLite)',
      'cachedOfflineLedger': 'Cached Offline Ledger (SQLite)',
      'liveLedger': 'Live Transactions',
      'optionalNotes': 'Optional Notes / Details',
      'notesHint': 'e.g. Copper wire bundle, 2 CRT monitors',
      'analyzingAi': 'Analyzing photo with AI...',
      'suggestedAi': 'Suggested by AI',
      'validWeightError': 'Please enter a valid weight (> 0 kg)',
      'lotSavedSuccess': 'Material lot saved locally in SQLite!',
      'language': 'Language',
      'categoryPcb': 'Motherboard / PCB',
      'categoryCopper': 'Copper Wire',
      'categoryBattery': 'Batteries',
      'categoryDisplay': 'Monitors & Displays',
      'categoryAppliances': 'Heavy Electricals',
      'categoryMixed': 'Mixed E-Waste',
      'lotDetails': 'Lot Details',
      'handoverToRecycler': 'Handover to Recycler',
      'selectRecycler': 'Select Authorized Recycler',
      'authorizedRecycler': 'Authorized Recycler',
      'confirmHandover': 'Confirm Handover & Payment',
      'handoverSuccess': 'Material handed over successfully!',
      'viewInLedger': 'View in Earnings Ledger',
      'checkPriceBoard': 'Check Market Price Board',
      'estimatedValue': 'Estimated Value',
      'transactionStatus': 'Transaction Status',
      'completed': 'Completed',
      'handoverSummary': 'Handover Summary',
      'lotStatus': 'Lot Status',
      'findRecycler': 'Find Recycler',
      'recyclerMatching': 'Recycler Matching',
      'recyclerDetails': 'Recycler Details',
      'distance': 'Distance',
      'rating': 'Rating',
      'handover': 'Handover',
      'generateQr': 'Generate QR',
      'scanQr': 'Scan QR',
      'handoverQr': 'Handover QR',
      'handoverConfirmed': 'Handover Confirmed',
      'waitingForConfirmation': 'Waiting for Recycler Confirmation',
      'readyForHandover': 'Ready for Handover',
      'handoverId': 'Handover ID',
      'confirmHandoverDemo': 'Simulate Recycler Confirmation (Demo)',
      'safety': 'Safety Guidance',
      'safetyFirst': 'Safety First',
      'wearGloves': 'Use Protective Gloves',
      'wearGlovesDesc': 'Wear durable protective gloves when sorting or carrying e-waste.',
      'batteryWarning': 'Do Not Break Batteries',
      'batteryWarningDesc': 'Do not puncture, crush, or open lithium or lead-acid batteries.',
      'doNotBurn': 'Never Burn E-Waste',
      'doNotBurnDesc': 'Burning wires or plastics releases toxic carcinogenic fumes.',
      'avoidLeaking': 'Avoid Leaking Chemicals',
      'avoidLeakingDesc': 'Keep clear of leaking capacitors and damaged screens.',
      'isolateDamaged': 'Isolate Damaged Components',
      'isolateDamagedDesc': 'Store cracked batteries or CRT tubes separately in a dry box.',
      'authorizedOnly': 'Hand Over to Authorized Recyclers',
      'authorizedOnlyDesc': 'Deliver hazardous e-waste to certified recycling centers.',
      'priceAlert': 'Price Alert',
      'setPriceAlert': 'Set Price Alert',
      'targetPrice': 'Target Price',
      'priceTarget': 'Price Target',
      'alertWhenReaches': 'Alert me when price reaches (₹/kg)',
      'notifications': 'Notifications',
      'notification': 'Notification',
      'noNotifications': 'No notifications right now.',
      'markAllRead': 'Mark All Read',
      'triggerPriceDemo': 'Trigger Price Spike Alert (Demo)',
      'mapView': 'Map View',
      'listView': 'List View',
      'locationPermissionDenied': 'Location permission unavailable (using central city reference).',
      'demoDataNotice': 'Demo / Mock Recycler Data',
      'proceedToHandover': 'Proceed to Handover',
      'acceptedMaterials': 'Accepted Materials',
      'viewMap': 'View on Map',
      'shareQr': 'Share QR Code',
      'myLots': 'My Lots',
      'lots': 'Lots',
      'recyclers': 'Recyclers',
      'about': 'About',
      'aboutApp': 'About / App Info',
      'appTagline': 'Connecting Collectors • Fair Prices • Formal Recycling',
      'versionInfo': 'Version 1.0.0',
      'aboutAppDescription': 'Kabadiwala Connect helps waste collectors identify recyclable materials, check market prices, find suitable recyclers, manage earnings, and complete safe e-waste handovers — even when internet connectivity is limited.',
      'whatYouCanDo': 'What you can do',
      'featureMaterialManagement': 'Material Management',
      'featureMaterialManagementDesc': 'Create and manage recyclable material lots.',
      'featurePriceBoard': 'Price Board',
      'featurePriceBoardDesc': 'Check indicative market prices for recyclable materials.',
      'featureFindRecyclers': 'Find Recyclers',
      'featureFindRecyclersDesc': 'Discover suitable recyclers based on material and proximity.',
      'featureSafeHandover': 'Safe Handover',
      'featureSafeHandoverDesc': 'Generate secure QR-based handover records.',
      'featureSafetyGuidance': 'Safety Guidance',
      'featureSafetyGuidanceDesc': 'Learn safe handling practices for electronic waste.',
      'featureEarnings': 'Earnings Ledger',
      'featureEarningsDesc': 'Track completed transactions and earnings.',
      'worksOffline': 'Works Offline',
      'worksOfflineDesc': 'Your records are stored locally and synchronized when connectivity is available.',
      'availableLanguages': 'Available in English • हिन्दी • मराठी',
      'close': 'Close',
      'noNotificationsYet': 'No notifications yet',
      'notificationEmptyDesc': "You'll see updates here when:\n• A recycler confirms a handover\n• A price alert is triggered",
      'errorLoadingNotifications': 'Unable to load notifications',
      'simulatePriceAlert': 'Simulate Price Spike Alert',
      'findingRecyclers': 'Finding nearby recyclers...',
      'matchesFound': 'Matches Found',
      'nearbyRecyclers': 'Nearby Recyclers',
      'noMatchingRecyclers': 'No matching recyclers found',
      'noMatchingRecyclersDesc': 'Try selecting a different material category or check back later.',
      'unableToLoadRecyclers': 'Unable to load recycler matches',
      'radarProximityView': 'Proximity Radar',
      'youReference': 'You',
      'startHandover': 'Start Handover',
      'viewDetails': 'View Details',
      'openStatus': 'Active',
      'kmAway': 'km away',
      'welcomeBack': 'Welcome back',
      'namaste': 'Namaste 👋',
      'loginPrompt': 'Login to continue using Kabadiwala Connect',
      'loginSubtitle': 'Enter your mobile number to receive OTP',
      'mobileNumber': 'Mobile Number',
      'enterMobileNumber': 'Enter 10-digit mobile number',
      'getOtp': 'Get OTP',
      'demoNumberHint': 'Demo: Tap to fill demo number',
      'validMobileError': 'Please enter a valid 10-digit mobile number',
      'verifyMobile': 'Verify Mobile Number',
      'otpSentTo': 'Enter the 6-digit OTP sent to',
      'enterOtp': 'Enter 6-digit OTP',
      'demoOtpHide': 'Demo OTP: 123456',
      'resendOtp': 'Resend OTP',
      'resendIn': 'Resend in',
      'seconds': 'sec',
      'changeNumber': 'Change Mobile Number',
      'verifyAndContinue': 'Verify & Continue',
      'otpMustBe6Digits': 'Please enter all 6 digits of the OTP',
      'incorrectOtp': 'Incorrect OTP. Please try again or use 123456',
      'completeProfile': 'Complete Your Profile',
      'profileSetupSubtitle': 'Just a few details to get you started',
      'fullName': 'Full Name',
      'enterFullName': 'Enter your name (e.g. Ramesh Shinde)',
      'nameRequiredError': 'Please enter your full name',
      'cityArea': 'Area / City',
      'enterCityArea': 'Enter your area or city (e.g. Pune)',
      'cityRequiredError': 'Please enter your area or city',
      'whatDoYouDo': 'What is your role?',
      'scrapCollector': 'Scrap Collector',
      'scrapCollectorDesc': 'Collects e-waste & scrap materials',
      'recyclerRole': 'Recycler',
      'recyclerRoleDesc': 'Authorized recycling center or partner',
      'addPhoto': 'Add Photo',
      'changePhoto': 'Change Photo',
      'saveAndContinue': 'Save & Continue',
      'welcomeOnboarding': 'Welcome to Kabadiwala Connect 👋',
      'onboardingSubtitle': 'Everything you need to manage your scrap collection in one place.',
      'onboardingStep1Title': 'Create Scrap Lots',
      'onboardingStep1Desc': 'Record e-waste materials with weights, photos & condition.',
      'onboardingStep2Title': 'Check Market Rates',
      'onboardingStep2Desc': 'View live & offline indicative rates with audio readout.',
      'onboardingStep3Title': 'Find Recyclers',
      'onboardingStep3Desc': 'Locate nearby authorized recycling centers easily.',
      'onboardingStep4Title': 'Track Earnings',
      'onboardingStep4Desc': 'Maintain an instant digital ledger of sales & payouts.',
      'onboardingStep5Title': 'Safe QR Handover',
      'onboardingStep5Desc': 'Hand over scrap safely with verified digital QR codes.',
      'getStarted': 'Get Started',
      'skip': 'Skip',
      'profile': 'Profile',
      'editProfile': 'Edit Profile',
      'saveChanges': 'Save Changes',
      'profileUpdated': 'Profile updated successfully!',
      'verifiedMobile': 'Verified Mobile',
      'cannotEditPhone': 'Mobile number is verified and linked to this account.',
      'helpSupport': 'Help & Support',
      'helpline': 'Kabadiwala Helpline',
      'helplineDesc': 'Toll-free collector assistance: 1800-267-3329 (9 AM - 7 PM)',
      'callHelpline': 'Call Helpline (1800-267-3329)',
      'logout': 'Logout',
      'logoutConfirmTitle': 'Logout Confirmation',
      'logoutConfirmMessage': 'Are you sure you want to logout? You will need to login again with your mobile number.',
      'cancel': 'Cancel',
      'loggedInSuccess': "You're logged in successfully.",
      'chooseFromGallery': 'Choose from Gallery',
      'takeCameraPhoto': 'Take Photo with Camera',
      'removePhoto': 'Remove Photo',
      'selectLanguage': 'Select Language',
      'collectorRoleBadge': 'Scrap Collector',
      'recyclerRoleBadge': 'Recycler',
      'welcomeLandingTitle': 'Welcome to Kabadiwala Connect',
      'welcomeLandingSubtitle': 'Sell, track and manage your scrap easily.',
      'login': 'Login',
      'createAccount': 'Create Account',
      'joinKabadiwala': 'Join Kabadiwala Connect',
      'createYourAccount': 'Create your account 👋',
      'welcomeBackLogin': 'Welcome back 👋',
      'loginToContinue': 'Login to continue to Kabadiwala Connect',
      'password': 'Password',
      'enterPassword': 'Enter password',
      'confirmPassword': 'Confirm Password',
      'enterConfirmPassword': 'Re-enter password',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'passwordLengthError': 'Password must be at least 6 characters.',
      'passwordsDoNotMatch': 'Passwords do not match.',
      'dontHaveAccount': "Don't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'accountAlreadyExists': 'An account with this mobile number already exists. Please login.',
      'invalidCredentialsError': 'Mobile number or password is incorrect.',
      'signUpOtpSubtitle': 'Enter the OTP sent to your mobile number to complete your registration.',
      'verifyMobileNumber': 'Verify your mobile number',
    },
    'hi': {
      'appTitle': 'कबाड़ीवाला कनेक्ट',
      'home': 'होम',
      'createLot': 'नया माल जोड़ें',
      'camera': 'कैमरा',
      'takePhoto': 'फोटो खींचें',
      'takePhotoPrompt': 'माल की फोटो खींचें या चुनें',
      'retake': 'पुनः लें',
      'retakePhoto': 'दूसरी फोटो लें',
      'chooseGallery': 'गैलरी से चुनें',
      'continueToDetails': 'आगे बढ़ें',
      'skipPhoto': 'बिना फोटो आगे बढ़ें',
      'material': 'सामग्री / माल',
      'selectCategory': 'माल का प्रकार चुनें',
      'weight': 'वजन',
      'enterWeight': 'वजन दर्ज करें (किग्रा)',
      'condition': 'हालत / स्थिति',
      'selectCondition': 'माल की हालत चुनें',
      'conditionGood': 'चालू (अच्छा)',
      'conditionAverage': 'मध्यम (पुराना)',
      'conditionScrap': 'कबाड़ (टूटा हुआ)',
      'save': 'सुरक्षित करें',
      'saveLot': 'माल सुरक्षित करें',
      'priceBoard': 'भाव बोर्ड',
      'indicativePrice': 'अनुमानित भाव',
      'listen': 'सुनें',
      'listening': 'आवाज़ बज रही है...',
      'earnings': 'कमाई',
      'earningsLedger': 'कमाई का खाता',
      'totalEarnings': 'कुल कमाई',
      'currentMonthEarnings': 'इस महीने की कमाई',
      'paid': 'भुगतान प्राप्त',
      'pending': 'बाकी',
      'paymentStatus': 'भुगतान स्थिति',
      'offline': 'ऑफ़लाइन',
      'offlineModeActive': 'ऑफ़लाइन मोड सक्रिय • माल SQLite में सुरक्षित है',
      'onlineConnected': 'ऑनलाइन • स्वतः क्लाउड सिंक चालू है',
      'noInternet': 'इंटरनेट नहीं है',
      'waitingForInternet': 'इंटरनेट की प्रतीक्षा है',
      'synced': 'सिंक हो गया',
      'syncing': 'सिंक हो रहा है...',
      'failed': 'विफल',
      'syncFailed': 'सिंक विफल',
      'pendingSync': 'सिंक बाकी',
      'retry': 'पुनः प्रयास करें',
      'retrySync': 'पुनः प्रयास करें',
      'syncNow': 'अभी सिंक करें',
      'lastUpdated': 'अंतिम अपडेट',
      'updatedToday': 'आज अपडेट किया गया',
      'noTransactions': 'अभी कोई लेन-देन दर्ज नहीं हुआ है।',
      'noLots': 'कोई माल दर्ज नहीं हुआ है।\n"नया माल जोड़ें" पर टैप करें।',
      'recordedLots': 'दर्ज माल',
      'source': 'स्रोत',
      'location': 'स्थान',
      'finalAmount': 'अंतिम राशि',
      'recycler': 'रिसायकलर',
      'refreshPrices': 'भाव ताज़ा करें',
      'refreshLedger': 'खाता ताज़ा करें',
      'allTransactions': 'सभी लेन-देन',
      'all': 'सभी',
      'indicativeRates': 'अनुमानित बाजार भाव',
      'liveRates': 'ताज़ा बाजार भाव',
      'cachedOfflineRates': 'ऑफ़लाइन सुरक्षित भाव (SQLite)',
      'cachedOfflineLedger': 'ऑफ़लाइन सुरक्षित खाता (SQLite)',
      'liveLedger': 'ताज़ा लेन-देन',
      'optionalNotes': 'अतिरिक्त जानकारी (वैकल्पिक)',
      'notesHint': 'जैसे: तांबे का तार बंडल, 2 मॉनिटर',
      'analyzingAi': 'एआई से फोटो की जांच हो रही है...',
      'suggestedAi': 'एआई द्वारा सुझाया गया',
      'validWeightError': 'कृपया सही वजन दर्ज करें (> 0 किग्रा)',
      'lotSavedSuccess': 'माल स्थानीय डेटाबेस में सुरक्षित हो गया!',
      'language': 'भाषा',
      'categoryPcb': 'मदरबोर्ड / पीसीबी (Motherboard)',
      'categoryCopper': 'तांबे का तार (Copper Wire)',
      'categoryBattery': 'बैटरी (Battery)',
      'categoryDisplay': 'मॉनिटर और स्क्रीन (Display)',
      'categoryAppliances': 'बिजली उपकरण (Appliances)',
      'categoryMixed': 'मिश्रित ई-कचरा (Mixed E-Waste)',
      'lotDetails': 'माल का विवरण',
      'handoverToRecycler': 'रिसायकलर को सौंपें',
      'selectRecycler': 'अधिकृत रिसायकलर चुनें',
      'authorizedRecycler': 'अधिकृत रिसायकलर',
      'confirmHandover': 'माल सौंपें और भुगतान दर्ज करें',
      'handoverSuccess': 'माल सफलतापूर्वक सौंप दिया गया!',
      'viewInLedger': 'कमाई खाते में देखें',
      'checkPriceBoard': 'बाजार भाव बोर्ड देखें',
      'estimatedValue': 'अनुमानित मूल्य',
      'transactionStatus': 'लेन-देन स्थिति',
      'completed': 'पूर्ण',
      'handoverSummary': 'हस्तांतरण सारांश',
      'lotStatus': 'माल की स्थिति',
      'findRecycler': 'रिसायकलर खोजें',
      'recyclerMatching': 'रिसायकलर मैचिंग',
      'recyclerDetails': 'रिसायकलर विवरण',
      'distance': 'दूरी',
      'rating': 'रेटिंग',
      'handover': 'हस्तांतरण',
      'generateQr': 'क्यूआर बनाएं',
      'scanQr': 'क्यूआर स्कैन करें',
      'handoverQr': 'हस्तांतरण क्यूआर',
      'handoverConfirmed': 'हस्तांतरण संपन्न',
      'waitingForConfirmation': 'रिसायकलर की पुष्टि की प्रतीक्षा है',
      'readyForHandover': 'हस्तांतरण के लिए तैयार',
      'handoverId': 'हस्तांतरण आईडी',
      'confirmHandoverDemo': 'रिसायकलर पुष्टि सिमुलेट करें (डेमो)',
      'safety': 'सुरक्षा मार्गदर्शन',
      'safetyFirst': 'सुरक्षा सर्वोपरि',
      'wearGloves': 'सुरक्षात्मक दस्ताने पहनें',
      'wearGlovesDesc': 'ई-कचरे को संभालते समय हमेशा सुरक्षा दस्ताने पहनें।',
      'batteryWarning': 'बैटरी को न तोड़ें',
      'batteryWarningDesc': 'बैटरी को छेदें, कुचलें या खोलें नहीं। इससे आग लग सकती है।',
      'doNotBurn': 'ई-कचरा कभी न जलाएं',
      'doNotBurnDesc': 'तार या प्लास्टिक जलाने से जहरीला और खतरनाक धुआं निकलता है।',
      'avoidLeaking': 'रिसाव वाले रसायनों से बचें',
      'avoidLeakingDesc': 'लीक हो रहे कैपेसिटर या स्क्रीन लिक्विड के सीधे संपर्क से बचें।',
      'isolateDamaged': 'क्षतिग्रस्त सामान अलग रखें',
      'isolateDamagedDesc': 'टूटी हुई बैटरियों को सूखी जगह पर अलग रखें।',
      'authorizedOnly': 'केवल अधिकृत रिसायकलर को दें',
      'authorizedOnlyDesc': 'हानिकारक ई-कचरा केवल प्रमाणित रिसायकलर को ही सौंपें।',
      'priceAlert': 'भाव अलर्ट',
      'setPriceAlert': 'भाव अलर्ट सेट करें',
      'targetPrice': 'लक्षित भाव',
      'priceTarget': 'लक्षित भाव',
      'alertWhenReaches': 'इस भाव पर पहुंचने पर मुझे सूचित करें (₹/किग्रा)',
      'notifications': 'सूचनाएं',
      'notification': 'सूचना',
      'noNotifications': 'अभी कोई नई सूचना नहीं है।',
      'markAllRead': 'सभी को पढ़ा हुआ चिह्नित करें',
      'triggerPriceDemo': 'भाव वृद्धि अलर्ट चलाएं (डेमो)',
      'mapView': 'नक्शा देखें',
      'listView': 'सूची देखें',
      'locationPermissionDenied': 'स्थान अनुमति उपलब्ध नहीं है (शहर के केंद्र का संदर्भ लिया जा रहा है)।',
      'demoDataNotice': 'डेमो रिसायकलर डेटा',
      'proceedToHandover': 'हस्तांतरण के लिए आगे बढ़ें',
      'acceptedMaterials': 'स्वीकृत सामग्री',
      'viewMap': 'नक्शे पर देखें',
      'shareQr': 'क्यूआर साझा करें',
      'myLots': 'मेरा माल',
      'lots': 'माल',
      'recyclers': 'रिसायकलर',
      'about': 'जानकारी',
      'aboutApp': 'कबाड़ीवाला कनेक्ट के बारे में',
      'appTagline': 'कलेक्टर्स को जोड़ना • उचित भाव • औपचारिक रिसायकलिंग',
      'versionInfo': 'संस्करण 1.0.0',
      'aboutAppDescription': 'कबाड़ीवाला कनेक्ट कबाड़ संग्राहकों को पुनर्चक्रण योग्य सामग्री की पहचान करने, बाजार भाव जांचने, उपयुक्त रिसायकलर खोजने, कमाई का प्रबंधन करने और सुरक्षित ई-कचरा हस्तांतरण पूरा करने में मदद करता है — कमजोर इंटरनेट में भी।',
      'whatYouCanDo': 'आप क्या कर सकते हैं',
      'featureMaterialManagement': 'सामग्री प्रबंधन',
      'featureMaterialManagementDesc': 'पुनर्चक्रण योग्य सामग्री के लॉट बनाएं और प्रबंधित करें।',
      'featurePriceBoard': 'भाव बोर्ड',
      'featurePriceBoardDesc': 'पुनर्चक्रण योग्य सामग्री के अनुमानित बाजार भाव देखें।',
      'featureFindRecyclers': 'रिसायकलर खोजें',
      'featureFindRecyclersDesc': 'सामग्री और नजदीकी के आधार पर उपयुक्त रिसायकलर खोजें।',
      'featureSafeHandover': 'सुरक्षित हस्तांतरण',
      'featureSafeHandoverDesc': 'सुरक्षित क्यूआर-आधारित हस्तांतरण रिकॉर्ड बनाएं।',
      'featureSafetyGuidance': 'सुरक्षा मार्गदर्शन',
      'featureSafetyGuidanceDesc': 'इलेक्ट्रॉनिक कचरा संभालने के सुरक्षित तरीके सीखें।',
      'featureEarnings': 'कमाई का खाता',
      'featureEarningsDesc': 'पूर्ण हुए लेन-देन और कमाई का हिसाब रखें।',
      'worksOffline': 'ऑफ़लाइन काम करता है',
      'worksOfflineDesc': 'आपके रिकॉर्ड स्थानीय रूप से सुरक्षित रहते हैं और इंटरनेट मिलने पर सिंक हो जाते हैं।',
      'availableLanguages': 'English • हिन्दी • मराठी में उपलब्ध',
      'close': 'बंद करें',
      'noNotificationsYet': 'अभी कोई नई सूचना नहीं है',
      'notificationEmptyDesc': "यहाँ आपको सूचनाएँ मिलेंगी जब:\n• रिसायकलर माल की पुष्टि करेगा\n• भाव अलर्ट सक्रिय होगा",
      'errorLoadingNotifications': 'सूचनाएँ लोड करने में असमर्थ',
      'simulatePriceAlert': 'भाव वृद्धि अलर्ट चलाएं',
      'findingRecyclers': 'नजदीकी रिसायकलर खोजे जा रहे हैं...',
      'matchesFound': 'मैच मिले',
      'nearbyRecyclers': 'नजदीकी रिसायकलर',
      'noMatchingRecyclers': 'कोई मेल खाता रिसायकलर नहीं मिला',
      'noMatchingRecyclersDesc': 'कृपया दूसरी सामग्री श्रेणी चुनें या बाद में पुनः प्रयास करें।',
      'unableToLoadRecyclers': 'रिसायकलर मैच लोड करने में असमर्थ',
      'radarProximityView': 'नजदीकी रडार',
      'youReference': 'आप / क्षेत्र',
      'startHandover': 'हस्तांतरण शुरू करें',
      'viewDetails': 'विवरण देखें',
      'openStatus': 'सक्रिय',
      'kmAway': 'किमी दूर',
      'welcomeBack': 'वापसी पर स्वागत है',
      'namaste': 'नमस्ते 👋',
      'loginPrompt': 'कबाडीवाला कनेक्ट जारी रखने के लिए लॉगिन करें',
      'loginSubtitle': 'ओटीपी प्राप्त करने के लिए अपना मोबाइल नंबर दर्ज करें',
      'mobileNumber': 'मोबाइल नंबर',
      'enterMobileNumber': '10-अंकों का मोबाइल नंबर दर्ज करें',
      'getOtp': 'ओटीपी प्राप्त करें',
      'demoNumberHint': 'डेमो: डेमो नंबर भरने के लिए टैप करें',
      'validMobileError': 'कृपया एक मान्य 10-अंकों का मोबाइल नंबर दर्ज करें',
      'verifyMobile': 'मोबाइल नंबर सत्यापित करें',
      'otpSentTo': 'इस नंबर पर भेजा गया 6-अंकों का ओटीपी दर्ज करें:',
      'enterOtp': '6-अंकों का ओटीपी दर्ज करें',
      'demoOtpHide': 'डेमो ओटीपी: 123456',
      'resendOtp': 'ओटीपी पुनः भेजें',
      'resendIn': 'पुनः भेजें',
      'seconds': 'सेकंड',
      'changeNumber': 'मोबाइल नंबर बदलें',
      'verifyAndContinue': 'सत्यापित करें और आगे बढ़ें',
      'otpMustBe6Digits': 'कृपया ओटीपी के सभी 6 अंक दर्ज करें',
      'incorrectOtp': 'गलत ओटीपी। कृपया पुनः प्रयास करें या 123456 का उपयोग करें',
      'completeProfile': 'अपनी प्रोफ़ाइल पूरी करें',
      'profileSetupSubtitle': 'शुरू करने के लिए बस कुछ बुनियादी जानकारी',
      'fullName': 'पूरा नाम',
      'enterFullName': 'अपना नाम दर्ज करें (उदा. रमेश शिंदे)',
      'nameRequiredError': 'कृपया अपना पूरा नाम दर्ज करें',
      'cityArea': 'क्षेत्र / शहर',
      'enterCityArea': 'अपना क्षेत्र या शहर दर्ज करें (उदा. पुणे)',
      'cityRequiredError': 'कृपया अपना क्षेत्र या शहर दर्ज करें',
      'whatDoYouDo': 'आपकी भूमिका क्या है?',
      'scrapCollector': 'कबाडीवाला / संग्राहक',
      'scrapCollectorDesc': 'ई-कचरा और भंगार सामग्री एकत्रित करता है',
      'recyclerRole': 'रिसायकलर',
      'recyclerRoleDesc': 'अधिकृत रिसायकलिंग केंद्र या भागीदार',
      'addPhoto': 'फोटो जोड़ें',
      'changePhoto': 'फोटो बदलें',
      'saveAndContinue': 'सहेजें और आगे बढ़ें',
      'welcomeOnboarding': 'कबाडीवाला कनेक्ट में आपका स्वागत है 👋',
      'onboardingSubtitle': 'आपके भंगार संग्रह को प्रबंधित करने के लिए सब कुछ एक ही स्थान पर।',
      'onboardingStep1Title': 'सामग्री लॉट बनाएं',
      'onboardingStep1Desc': 'वजन, फोटो और स्थिति के साथ ई-कचरा सामग्री दर्ज करें।',
      'onboardingStep2Title': 'बाजार दर देखें',
      'onboardingStep2Desc': 'ऑडियो सहायता के साथ वास्तविक और ऑफ़लाइन बाजार दर देखें।',
      'onboardingStep3Title': 'रिसायकलर खोजें',
      'onboardingStep3Desc': 'निकटतम प्रमाणित रिसायकलर केंद्रों से आसानी से जुड़ें।',
      'onboardingStep4Title': 'कमाई का हिसाब रखें',
      'onboardingStep4Desc': 'सभी बिक्री और भुगतानों का तुरंत डिजिटल खाता बनाए रखें।',
      'onboardingStep5Title': 'सुरक्षित क्यूआर हस्तांतरण',
      'onboardingStep5Desc': 'प्रमाणित डिजिटल क्यूआर कोड के साथ सामग्री सुरक्षित रूप से सौंपें।',
      'getStarted': 'शुरू करें',
      'skip': 'छोड़ें',
      'profile': 'प्रोफ़ाइल',
      'editProfile': 'प्रोफ़ाइल संपादित करें',
      'saveChanges': 'बदलाव सहेजें',
      'profileUpdated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
      'verifiedMobile': 'सत्यापित मोबाइल',
      'cannotEditPhone': 'मोबाइल नंबर सत्यापित है और इस खाते से जुड़ा हुआ है।',
      'helpSupport': 'सहायता और समर्थन',
      'helpline': 'कबाडीवाला हेल्पलाइन',
      'helplineDesc': 'टोल-फ्री कलेक्टर सहायता: 1800-267-3329 (सुबह 9 से शाम 7 बजे)',
      'callHelpline': 'हेल्पलाइन पर कॉल करें (1800-267-3329)',
      'logout': 'लॉगआउट',
      'logoutConfirmTitle': 'लॉगआउट की पुष्टि',
      'logoutConfirmMessage': 'क्या आप निश्चित रूप से लॉगआउट करना चाहते हैं? दोबारा लॉगिन करने के लिए आपको अपने मोबाइल नंबर की आवश्यकता होगी।',
      'cancel': 'रद्द करें',
      'loggedInSuccess': 'आप सफलतापूर्वक लॉगिन हो गए हैं।',
      'chooseFromGallery': 'गैलरी से चुनें',
      'takeCameraPhoto': 'कैमरे से फोटो लें',
      'removePhoto': 'फोटो हटाएं',
      'selectLanguage': 'भाषा चुनें',
      'collectorRoleBadge': 'कबाडीवाला / संग्राहक',
      'recyclerRoleBadge': 'रिसायकलर',
      'welcomeLandingTitle': 'कबाड़ीवाला कनेक्ट में आपका स्वागत है',
      'welcomeLandingSubtitle': 'अपने कबाड़ को आसानी से बेचें, ट्रैक करें और प्रबंधित करें।',
      'login': 'लॉगिन करें',
      'createAccount': 'खाता बनाएं',
      'joinKabadiwala': 'कबाड़ीवाला कनेक्ट से जुड़ें',
      'createYourAccount': 'अपना खाता बनाएं 👋',
      'welcomeBackLogin': 'वापसी पर स्वागत है 👋',
      'loginToContinue': 'कबाड़ीवाला कनेक्ट जारी रखने के लिए लॉगिन करें',
      'password': 'पासवर्ड',
      'enterPassword': 'पासवर्ड दर्ज करें',
      'confirmPassword': 'पासवर्ड की पुष्टि करें',
      'enterConfirmPassword': 'पासवर्ड दोबारा दर्ज करें',
      'showPassword': 'पासवर्ड दिखाएं',
      'hidePassword': 'पासवर्ड छुपाएं',
      'passwordLengthError': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'passwordsDoNotMatch': 'पासवर्ड मेल नहीं खाते।',
      'dontHaveAccount': 'क्या आपका खाता नहीं है?',
      'alreadyHaveAccount': 'क्या आपके पास पहले से खाता है?',
      'accountAlreadyExists': 'इस मोबाइल नंबर वाला खाता पहले से मौजूद है। कृपया लॉगिन करें।',
      'invalidCredentialsError': 'मोबाइल नंबर या पासवर्ड गलत है।',
      'signUpOtpSubtitle': 'अपना पंजीकरण पूरा करने के लिए अपने मोबाइल नंबर पर भेजा गया ओटीपी दर्ज करें।',
      'verifyMobileNumber': 'अपना मोबाइल नंबर सत्यापित करें',
    },
    'mr': {
      'appTitle': 'कबाडीवाला कनेक्ट',
      'home': 'होम',
      'createLot': 'नवीन माल नोंदवा',
      'camera': 'कॅमेरा',
      'takePhoto': 'फोटो काढा',
      'takePhotoPrompt': 'मालाचा फोटो काढा किंवा निवडा',
      'retake': 'पुन्हा घ्या',
      'retakePhoto': 'दुसरा फोटो काढा',
      'chooseGallery': 'गॅलरीतून निवडा',
      'continueToDetails': 'पुढे जा',
      'skipPhoto': 'फोटो न घेता पुढे जा',
      'material': 'मालाचा प्रकार',
      'selectCategory': 'मालाचा प्रकार निवडा',
      'weight': 'वजन',
      'enterWeight': 'वजन प्रविष्ट करा (किलो)',
      'condition': 'स्थिती',
      'selectCondition': 'मालाची स्थिती निवडा',
      'conditionGood': 'चालू (चांगली)',
      'conditionAverage': 'मध्यम (वापरलेले)',
      'conditionScrap': 'स्क्रॅप (तुटलेले)',
      'save': 'जतन करा',
      'saveLot': 'माल जतन करा',
      'priceBoard': 'दर फलक',
      'indicativePrice': 'अंदाजे दर',
      'listen': 'ऐका',
      'listening': 'आवाज सुरू आहे...',
      'earnings': 'कमाई',
      'earningsLedger': 'कमाईचे खाते',
      'totalEarnings': 'एकूण कमाई',
      'currentMonthEarnings': 'या महिन्याची कमाई',
      'paid': 'भरणा झाला',
      'pending': 'प्रलंबित',
      'paymentStatus': 'पेमेंट स्थिती',
      'offline': 'ऑफलाइन',
      'offlineModeActive': 'ऑफलाइन मोड सक्रिय • माल SQLite मध्ये जतन आहे',
      'onlineConnected': 'ऑनलाइन • स्वयंचलित क्लाउड सिंक सुरू आहे',
      'noInternet': 'इंटरनेट नाही',
      'waitingForInternet': 'इंटरनेटची प्रतीक्षा आहे',
      'synced': 'सिंक झाले',
      'syncing': 'सिंक होत आहे...',
      'failed': 'अयशस्वी',
      'syncFailed': 'सिंक अयशस्वी',
      'pendingSync': 'सिंक बाकी',
      'retry': 'पुन्हा प्रयत्न करा',
      'retrySync': 'पुन्हा प्रयत्न करा',
      'syncNow': 'आता सिंक करा',
      'lastUpdated': 'शेवटचे अपडेट',
      'updatedToday': 'आज अपडेट केले',
      'noTransactions': 'अद्याप कोणतेही व्यवहार नोंदवलेले नाहीत.',
      'noLots': 'अद्याप कोणताही माल नोंदवलेला नाही.\n"नवीन माल नोंदवा" वर टॅप करा.',
      'recordedLots': 'नोंदवलेला माल',
      'source': 'स्रोत',
      'location': 'ठिकाण',
      'finalAmount': 'अंतिम रक्कम',
      'recycler': 'रिसायकलर',
      'refreshPrices': 'दर रिफ्रेश करा',
      'refreshLedger': 'खाते रिफ्रेश करा',
      'allTransactions': 'सर्व व्यवहार',
      'all': 'सर्व',
      'indicativeRates': 'अंदाजे बाजार दर',
      'liveRates': 'ताजे बाजार दर',
      'cachedOfflineRates': 'ऑफलाइन जतन केलेले दर (SQLite)',
      'cachedOfflineLedger': 'ऑफलाइन जतन केलेले खाते (SQLite)',
      'liveLedger': 'ताजे व्यवहार',
      'optionalNotes': 'अधिक माहिती (पर्यायी)',
      'notesHint': 'उदा. तांब्याची तार बंडल, 2 मॉनिटर',
      'analyzingAi': 'एआय द्वारे फोटो तपासला जात आहे...',
      'suggestedAi': 'एआय द्वारे सुचवलेले',
      'validWeightError': 'कृपया योग्य वजन प्रविष्ट करा (> 0 किलो)',
      'lotSavedSuccess': 'माल स्थानिक डेटाबेसमध्ये जतन झाला!',
      'language': 'भाषा',
      'categoryPcb': 'मदरबोर्ड / पीसीबी (Motherboard)',
      'categoryCopper': 'तांब्याची तार (Copper Wire)',
      'categoryBattery': 'बॅटरी (Battery)',
      'categoryDisplay': 'मॉनिटर आणि स्क्रीन (Display)',
      'categoryAppliances': 'विद्युत उपकरणे (Appliances)',
      'categoryMixed': 'मिश्र ई-कचरा (Mixed E-Waste)',
      'lotDetails': 'मालाचा तपशील',
      'handoverToRecycler': 'रिसायकलरला माल द्या',
      'selectRecycler': 'अधिकृत रिसायकलर निवडा',
      'authorizedRecycler': 'अधिकृत रिसायकलर',
      'confirmHandover': 'माल देणे व पेमेंट निश्चित करा',
      'handoverSuccess': 'माल यशस्वीरित्या देण्यात आला!',
      'viewInLedger': 'कमाईच्या खात्यात पहा',
      'checkPriceBoard': 'बाजार दर फलक पहा',
      'estimatedValue': 'अंदाजे मूल्य',
      'transactionStatus': 'व्यवहार स्थिती',
      'completed': 'पूर्ण',
      'handoverSummary': 'हस्तांतरण सारांश',
      'lotStatus': 'मालाची स्थिती',
      'findRecycler': 'रिसायकलर शोधा',
      'recyclerMatching': 'रिसायकलर जुळणी',
      'recyclerDetails': 'रिसायकलर माहिती',
      'distance': 'अंतर',
      'rating': 'रेटिंग',
      'handover': 'हस्तांतरण',
      'generateQr': 'क्यूआर तयार करा',
      'scanQr': 'क्यूआर स्कॅन करा',
      'handoverQr': 'हस्तांतरण क्यूआर',
      'handoverConfirmed': 'हस्तांतरण पूर्ण झाले',
      'waitingForConfirmation': 'रिसायकलरच्या पुष्टीची प्रतीक्षा आहे',
      'readyForHandover': 'हस्तांतरणासाठी तयार',
      'handoverId': 'हस्तांतरण आयडी',
      'confirmHandoverDemo': 'रिसायकलर पुष्टी सिमुलेट करा (डेमो)',
      'safety': 'सुरक्षा मार्गदर्शन',
      'safetyFirst': 'सुरक्षा सर्वप्रथम',
      'wearGloves': 'संरक्षक हातमोजे वापरा',
      'wearGlovesDesc': 'ई-कचरा हाताळताना नेहमी संरक्षक हातमोजे वापरा.',
      'batteryWarning': 'बॅटरी फोडू नका',
      'batteryWarningDesc': 'बॅटरी कापू, चेपू किंवा उघडू नका. यामुळे आग लागू शकते.',
      'doNotBurn': 'ई-कचरा कधीही जाळू नका',
      'doNotBurnDesc': 'वायर किंवा प्लास्टिक जाळल्याने विषारी धूर निघतो.',
      'avoidLeaking': 'गळती असलेल्या रसायनांपासून सावध राहा',
      'avoidLeakingDesc': 'गळणारे कपॅसिटर किंवा स्क्रीन लिक्विडच्या थेट संपर्कापासून दूर राहा.',
      'isolateDamaged': 'खराब झालेले सामान वेगळे ठेवा',
      'isolateDamagedDesc': 'खराब झालेल्या बॅटऱ्या कोरड्या जागी वेगळ्या ठेवा.',
      'authorizedOnly': 'फक्त अधिकृत रिसायकलरला द्या',
      'authorizedOnlyDesc': 'धोकादायक ई-कचरा केवळ प्रमाणित रिसायकलरकडेच द्या.',
      'priceAlert': 'दर अलर्ट',
      'setPriceAlert': 'दर अलर्ट सेट करा',
      'targetPrice': 'अपेक्षित दर',
      'priceTarget': 'अपेक्षित दर',
      'alertWhenReaches': 'हा दर गाठल्यावर मला सूचना द्या (₹/किलो)',
      'notifications': 'सूचना',
      'notification': 'सूचना',
      'noNotifications': 'सध्या कोणतीही सूचना नाही.',
      'markAllRead': 'सर्व वाचल्याचे चिन्हांकित करा',
      'triggerPriceDemo': 'दर वाढ अलर्ट सुरू करा (डेमो)',
      'mapView': 'नकाशा पहा',
      'listView': 'यादी पहा',
      'locationPermissionDenied': 'स्थान परवानगी उपलब्ध नाही (शहराच्या मध्यवर्ती भागाचा संदर्भ वापरला जात आहे).',
      'demoDataNotice': 'डेमो रिसायकलर डेटा',
      'proceedToHandover': 'हस्तांतरणासाठी पुढे जा',
      'acceptedMaterials': 'स्वीकारलेले माल',
      'viewMap': 'नकाशावर पहा',
      'shareQr': 'क्यूआर शेअर करा',
      'myLots': 'माझा माल',
      'lots': 'माल',
      'recyclers': 'रिसायकलर',
      'about': 'माहिती',
      'aboutApp': 'कबाडीवाला कनेक्टबद्दल',
      'appTagline': 'कलेक्टर्सना जोडणे • योग्य दर • अधिकृत रिसायकलिंग',
      'versionInfo': 'आवृत्ती 1.0.0',
      'aboutAppDescription': 'कबाडीवाला कनेक्ट कचरा वेचकांना पुनर्वापरयोग्य वस्तू ओळखणे, बाजार दर तपासणे, योग्य रिसायकलर शोधणे, कमाईचे व्यवस्थापन करणे आणि सुरक्षित ई-कचरा हस्तांतरण पूर्ण करण्यास मदत करते — अगदी मर्यादित इंटरनेट असतानाही.',
      'whatYouCanDo': 'तुम्ही काय करू शकता',
      'featureMaterialManagement': 'सामग्री व्यवस्थापन',
      'featureMaterialManagementDesc': 'पुनर्वापरयोग्य मालाची नोंद आणि व्यवस्थापन करा.',
      'featurePriceBoard': 'दर फलक',
      'featurePriceBoardDesc': 'पुनर्वापरयोग्य मालाचे अंदाजे बाजार दर तपासा.',
      'featureFindRecyclers': 'रिसायकलर शोधा',
      'featureFindRecyclersDesc': 'मालाचा प्रकार आणि अंतरावर आधारित योग्य रिसायकलर शोधा.',
      'featureSafeHandover': 'सुरक्षित हस्तांतरण',
      'featureSafeHandoverDesc': 'सुरक्षित क्यूआर-आधारित हस्तांतरण नोंदी तयार करा.',
      'featureSafetyGuidance': 'सुरक्षा मार्गदर्शन',
      'featureSafetyGuidanceDesc': 'ई-कचरा हाताळण्याच्या सुरक्षित पद्धती जाणून घ्या.',
      'featureEarnings': 'कमाईचे खाते',
      'featureEarningsDesc': 'पूर्ण झालेले व्यवहार आणि कमाईचा हिशोब ठेवा.',
      'worksOffline': 'ऑफलाइन कार्य करते',
      'worksOfflineDesc': 'तुमच्या नोंदी स्थानिक पातळीवर सुरक्षित राहतात आणि इंटरनेट उपलब्ध झाल्यावर सिंक होतात.',
      'availableLanguages': 'English • हिन्दी • मराठी मध्ये उपलब्ध',
      'close': 'बंद करा',
      'noNotificationsYet': 'अद्याप कोणतीही सूचना नाही',
      'notificationEmptyDesc': "येथे तुम्हाला सूचना मिळतील जेव्हा:\n• रिसायकलर मालाची पुष्टी करेल\n• दर अलर्ट सक्रिय होईल",
      'errorLoadingNotifications': 'सूचना लोड करण्यात अयशस्वी',
      'simulatePriceAlert': 'दर वाढ अलर्ट सुरू करा',
      'findingRecyclers': 'जवळचे रिसायकलर शोधत आहे...',
      'matchesFound': 'जुळणी सापडली',
      'nearbyRecyclers': 'जवळचे रिसायकलर',
      'noMatchingRecyclers': 'कोणताही जुळणारा रिसायकलर आढळला नाही',
      'noMatchingRecyclersDesc': 'कृपया दुसरा मालाचा प्रकार निवडा किंवा नंतर पुन्हा प्रयत्न करा.',
      'unableToLoadRecyclers': 'रिसायकलर लोड करण्यात अयशस्वी',
      'radarProximityView': 'नजीकचा रडार',
      'youReference': 'तुम्ही / परिसर',
      'startHandover': 'हस्तांतरण सुरू करा',
      'viewDetails': 'माहिती पहा',
      'openStatus': 'सक्रिय',
      'kmAway': 'किमी दूर',
      'welcomeBack': 'पुन्हा स्वागत आहे',
      'namaste': 'नमस्ते 👋',
      'loginPrompt': 'कबाडीवाला कनेक्ट वापरणे सुरू ठेवण्यासाठी लॉगिन करा',
      'loginSubtitle': 'ओटीपी मिळवण्यासाठी तुमचा मोबाइल नंबर टाका',
      'mobileNumber': 'मोबाइल नंबर',
      'enterMobileNumber': '10-अंकी मोबाइल नंबर टाका',
      'getOtp': 'ओटीपी मिळवा',
      'demoNumberHint': 'डेमो: डेमो नंबर भरण्यासाठी टॅप करा',
      'validMobileError': 'कृपया वैध 10-अंकी मोबाइल नंबर टाका',
      'verifyMobile': 'मोबाइल नंबर पडताळा',
      'otpSentTo': 'या क्रमांकावर पाठवलेला 6-अंकी ओटीपी टाका:',
      'enterOtp': '6-अंकी ओटीपी टाका',
      'demoOtpHide': 'डेमो ओटीपी: 123456',
      'resendOtp': 'ओटीपी पुन्हा पाठवा',
      'resendIn': 'पुन्हा पाठवा',
      'seconds': 'सेकंद',
      'changeNumber': 'मोबाइल नंबर बदला',
      'verifyAndContinue': 'पडताळा आणि पुढे जा',
      'otpMustBe6Digits': 'कृपया ओटीपीचे सर्व 6 अंक टाका',
      'incorrectOtp': 'चुकीचा ओटीपी. कृपया पुन्हा प्रयत्न करा किंवा 123456 वापरा',
      'completeProfile': 'तुमचे प्रोफाइल पूर्ण करा',
      'profileSetupSubtitle': 'सुरू करण्यासाठी फक्त काही मूलभूत माहिती',
      'fullName': 'पूर्ण नाव',
      'enterFullName': 'तुमचे नाव टाका (उदा. रमेश शिंदे)',
      'nameRequiredError': 'कृपया तुमचे पूर्ण नाव टाका',
      'cityArea': 'परिसर / शहर',
      'enterCityArea': 'तुमचा परिसर किंवा शहर टाका (उदा. पुणे)',
      'cityRequiredError': 'कृपया तुमचा परिसर किंवा शहर टाका',
      'whatDoYouDo': 'तुमची भूमिका काय आहे?',
      'scrapCollector': 'भंगार वेचक / संग्राहक',
      'scrapCollectorDesc': 'ई-कचरा आणि भंगार माल गोळा करतो',
      'recyclerRole': 'रिसायकलर',
      'recyclerRoleDesc': 'अधिकृत रिसायकलिंग केंद्र किंवा भागीदार',
      'addPhoto': 'फोटो जोडा',
      'changePhoto': 'फोटो बदला',
      'saveAndContinue': 'जतन करा आणि पुढे जा',
      'welcomeOnboarding': 'कबाडीवाला कनेक्ट मध्ये आपले स्वागत आहे 👋',
      'onboardingSubtitle': 'तुमच्या भंगार संकलनाचे व्यवस्थापन करण्यासाठी सर्व काही एकाच ठिकाणी.',
      'onboardingStep1Title': 'मालाची नोंद करा',
      'onboardingStep1Desc': 'वजन, फोटो आणि स्थितीसह ई-कचरा मालाची नोंद करा.',
      'onboardingStep2Title': 'बाजार दर तपासा',
      'onboardingStep2Desc': 'ऑडिओ वाचनासह थेट आणि ऑफलाइन बाजार दर पहा.',
      'onboardingStep3Title': 'रिसायकलर शोधा',
      'onboardingStep3Desc': 'जवळच्या अधिकृत रिसायकलर्सशी सहज संपर्क साधा.',
      'onboardingStep4Title': 'कमाईचा हिशोब ठेवा',
      'onboardingStep4Desc': 'सर्व व्यवहार आणि कमाईची त्वरित डिजिटल नोंद ठेवा.',
      'onboardingStep5Title': 'सुरक्षित क्यूआर हस्तांतरण',
      'onboardingStep5Desc': 'पडताळणी केलेल्या डिजिटल क्यूआर कोडसह माल सुरक्षितपणे हस्तांतरित करा.',
      'getStarted': 'सुरू करा',
      'skip': 'वगळा',
      'profile': 'प्रोफाइल',
      'editProfile': 'प्रोफाइल संपादित करा',
      'saveChanges': 'बदल जतन करा',
      'profileUpdated': 'प्रोफाइल यशस्वीरित्या अपडेट झाली!',
      'verifiedMobile': 'पडताळलेला मोबाइल',
      'cannotEditPhone': 'मोबाइल नंबर पडताळलेला आहे आणि या खात्याशी जोडलेला आहे.',
      'helpSupport': 'मदत आणि सहकार्य',
      'helpline': 'कबाडीवाला हेल्पलाइन',
      'helplineDesc': 'टोल-फ्री कलेक्टर मदत: 1800-267-3329 (सकाळी 9 ते संध्याकाळी 7)',
      'callHelpline': 'हेल्पलाइनवर कॉल करा (1800-267-3329)',
      'logout': 'लॉगआउट',
      'logoutConfirmTitle': 'लॉगआउटची खात्री',
      'logoutConfirmMessage': 'तुम्हाला खात्री आहे की तुम्ही लॉगआउट करू इच्छिता? पुन्हा लॉगिन करण्यासाठी तुम्हाला तुमच्या मोबाइल नंबरची आवश्यकता असेल.',
      'cancel': 'रद्द करा',
      'loggedInSuccess': 'तुम्ही यशस्वीरित्या लॉगिन झाला आहात.',
      'chooseFromGallery': 'गॅलरीतून निवडा',
      'takeCameraPhoto': 'कॅमेऱ्याने फोटो काढा',
      'removePhoto': 'फोटो काढा',
      'selectLanguage': 'भाषा निवडा',
      'collectorRoleBadge': 'भंगार वेचक / संग्राहक',
      'recyclerRoleBadge': 'रिसायकलर',
      'welcomeLandingTitle': 'कबाडीवाला कनेक्ट मध्ये आपले स्वागत आहे',
      'welcomeLandingSubtitle': 'तुमचा भंगार सहजपणे विका, मागोवा घ्या आणि व्यवस्थापित करा.',
      'login': 'लॉगिन करा',
      'createAccount': 'खाते तयार करा',
      'joinKabadiwala': 'कबाडीवाला कनेक्ट मध्ये सामील व्हा',
      'createYourAccount': 'आपले खाते तयार करा 👋',
      'welcomeBackLogin': 'परत स्वागत आहे 👋',
      'loginToContinue': 'कबाडीवाला कनेक्ट सुरू ठेवण्यासाठी लॉगिन करा',
      'password': 'पासवर्ड',
      'enterPassword': 'पासवर्ड प्रविष्ट करा',
      'confirmPassword': 'पासवर्डची पुष्टी करा',
      'enterConfirmPassword': 'पासवर्ड पुन्हा प्रविष्ट करा',
      'showPassword': 'पासवर्ड दाखवा',
      'hidePassword': 'पासवर्ड लपवा',
      'passwordLengthError': 'पासवर्ड किमान 6 अक्षरांचा असावा.',
      'passwordsDoNotMatch': 'पासवर्ड जुळत नाहीत.',
      'dontHaveAccount': 'खाते नाही का?',
      'alreadyHaveAccount': 'आधीच खाते आहे का?',
      'accountAlreadyExists': 'या मोबाइल नंबरचे खाते आधीपासून अस्तित्वात आहे. कृपया लॉगिन करा.',
      'invalidCredentialsError': 'मोबाइल नंबर किंवा पासवर्ड चुकीचा आहे.',
      'signUpOtpSubtitle': 'तुमची नोंदणी पूर्ण करण्यासाठी तुमच्या मोबाइल नंबरवर पाठवलेला OTP प्रविष्ट करा.',
      'verifyMobileNumber': 'तुमचा मोबाइल नंबर पडताळा',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'hi', 'mr'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
